### ISSUE TITLE
KR-global_conf.json

### ISSUE THREAD

**Issue by oyj0594** [TheThingsNetwork/gateway-conf#24] opened 2017-10-16 11:18 UTC
Hi,
in your KR-global_conf.json file, there is IF value 600000 and -600000. 
it seems IF value is limited by semtech lora gateway HAL. 

how can i fix this value while following KR's channel plan?

**Comment by jpmeijers** [comment] 2017-10-16 16:49
Marking as duplicate of #23

**Comment by oyj0594** [comment] 2017-10-21 09:25
So, have you tested conf file for packet forwarder??
it works at lora-gateway util_pkt_logger, however , not on lora_pkt_fwd..

**Comment by jpmeijers** [comment] 2017-10-22 13:58
@oyj0594 Can you please test the updated config: https://github.com/TheThingsNetwork/gateway-conf/blob/jpmeijers-patch-1/KR-global_conf.json

**Comment by oyj0594** [comment] 2017-10-23 01:30
i already have tested it but it didn't work at https://github.com/Lora-net/packet_forwarder/tree/master/lora_pkt_fwd
it only works at https://github.com/Lora-net/lora_gateway/tree/master/util_pkt_logger

**Closed as completed** 2017-10-23 08:21 UTC
Labels: duplicate

**Comment by jpmeijers** [comment] 2017-10-23 10:20
@oyj0594 When you say it doesn't work, do you get an error output from the packet forwarder? Can you please send us the error log to investigate?

**Comment by oyj0594** [comment] 2017-10-23 12:39
sorry. i miss-configured something. it works fine. 
thanks for your support!
